#!/bin/bash
# Test ingestion trigger script

# Your session cookie (copy the entire cookie string from browser)
COOKIE="__next_hmr_refresh_hash__=76ac3ddb70b304db73eaea9ebdc74f2721faa5cd43f7aa38; sb-mddgtexrnnlctttbcpsy-auth-token.0=base64-eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0ltdHBaQ0k2SW1ackwxWmtVSEJ2Vm5wVmFUWkNPVUlpTENKMGVYQWlPaUpLVjFRaWZRLmV5SnBjM01pT2lKb2RIUndjem92TDIxa1pHZDBaWGh5Ym01c1kzUjBkR0pqY0hONUxuTjFjR0ZpWVhObExtTnZMMkYxZEdndmRqRWlMQ0p6ZFdJaU9pSmpOMlk1TTJWaE1DMWxOVGt4TFRRek16WXRPRE5sTWkwNU1EQmlOemRoTkRoaE5tRWlMQ0poZFdRaU9pSmhkWFJvWlc1MGFXTmhkR1ZrSWl3aVpYaHdJam94TnpZeU16QXlNRFkwTENKcFlYUWlPakUzTmpJeU9UZzBOalFzSW1WdFlXbHNJam9pYzJGeWJXRmtZelExUUdkdFlXbHNMbU52YlNJc0luQm9iMjVsSWpvaUlpd2lZWEJ3WDIxbGRHRmtZWFJoSWpwN0luQnliM1pwWkdWeUlqb2laMjl2WjJ4bElpd2ljSEp2ZG1sa1pYSnpJanBiSW1kdmIyZHNaU0pkZlN3aWRYTmxjbDl0WlhSaFpHRjBZU0k2ZXlKbGJXRnBiQ0k2SW5OaGNtMWhaR00wTlVCbmJXRnBiQzVqYjIwaUxDSmxiV0ZwYkY5MlpYSnBabWxsWkNJNmRISjFaU3dpWm5Wc2JGOXVZVzFsSWpvaVUyRnliV0ZrSUVOb1pXVnRZU0lzSW1semN5STZJbWgwZEhCek9pOHZZV05qYjNWdWRITXVaMjl2WjJ4bExtTnZiU0lzSW01aGJXVWlPaUpUWVhKdFlXUWdRMmhsWlcxaElpd2ljR2h2Ym1WZmRtVnlhV1pwWldRaU9tWmhiSE5sTENKd2NtOTJhV1JsY2w5cFpDSTZJakV3TWpJNE5UY3pORGczTmpFMk9EVTNOemMyTXlJc0luTjFZaUk2SWpFd01qSTROVGN6TkRnM05qRTJPRFUzTnpjMk15SjlMQ0p5YjJ4bElqb2lZWFYwYUdWdWRHbGpZWFJsWkNJc0ltRmhiQ0k2SW1GaGJERWlMQ0poYlhJaU9sdDdJbTFsZEdodlpDSTZJbTloZFhSb0lpd2lkR2x0WlhOMFlXMXdJam94TnpZeE9UWXpORFkzZlYwc0luTmxjM05wYjI1ZmFXUWlPaUl3WldJM1lqWmlNaTA1TjJZMkxUUXhaVFl0T1RsaE15MHpPRGcyTUdabU5ETTBZakFpTENKcGMxOWhibTl1ZVcxdmRYTWlPbVpoYkhObGZRLjBTdUlBSUZTcjZFXzJ2MmFsN0wwVi04b3ZxLWRkd2FVSUFyVm5iVl9NUVEiLCJ0b2tlbl90eXBlIjoiYmVhcmVyIiwiZXhwaXJlc19pbiI6MzYwMCwiZXhwaXJlc19hdCI6MTc2MjMwMjA2NCwicmVmcmVzaF90b2tlbiI6InFmenVrZW9pYXpzYSIsInVzZXIiOnsiaWQiOiJjN2Y5M2VhMC1lNTkxLTQzMzYtODNlMi05MDBiNzdhNDhhNmEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJlbWFpbCI6InNhcm1hZGM0NUBnbWFpbC5jb20iLCJlbWFpbF9jb25maXJtZWRfYXQiOiIyMDI1LTA3LTE4VDIxOjI5OjQ2LjM4NTk5MVoiLCJwaG9uZSI6IiIsImNvbmZpcm1lZF9hdCI6IjIwMjUtMDctMThUMjE6Mjk6NDYuMzg1OTkxWiIsImxhc3Rfc2lnbl9pbl9hdCI6IjIwMjUtMTEtMDFUMTg6NDY6MDQuMzExMDA2WiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6Imdvb2dsZSIsInByb3ZpZGVycyI6WyJnb29nbGUiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiJzYXJtYWRjNDVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6IlNhcm1hZCBDaGVlbWEiLCJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYW1lIjoiU2FybWFkIENoZWVtYSIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwicHJvdmlkZXJfaWQiOiIxMDIyODU3MzQ4NzYxNjg1Nzc3NjMiLCJzdWIiOiIxMDIyODU3MzQ4NzYxNjg1Nzc3NjMifSwiaWRlbnRpdGllcyI6W3siaWRlbnRpdHlfaWQiOiI5MzhjODM3NC04MzdiLTQ4MGQtYmJiNi05NTNkN2QyZmQwYTciLCJpZCI6IjEwMjI4NTczNDg3NjE2ODU3Nzc2MyIsInVzZXJfaWQiOiJjN2Y5M2VhMC1lNTkxLTQzMzYtODNlMi05MDBiNzdhNDhhNmEiLCJpZGVudGl0eV9kYXRhIjp7ImVtYWlsIjoic2FybWFkYzQ1QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJTYXJtYWQgQ2hlZW1hIiwiaXNzIjoiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tIiwibmFtZSI6IlNhcm1hZCBDaGVlbWEiLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInByb3ZpZGVyX2lkIjoiMTAyMjg1NzM0ODc2MTY4NTc3NzYzIiwic3ViIjoiMTAyMjg1NzM0ODc2MTY4NTc3NzYzIn0sInByb3ZpZGVyIjoiZ29vZ2xlIiwibGFzdF9zaWduX2luX2F0IjoiMjAyNS0wNy0xOFQyMToyOTo0Ni4zNzU2MzhaIiwiY3JlYXRlZF9hdCI6IjIwMjUtMDctMThUMjE6Mjk6NDYuMzc1Njk0WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTExLTAxVDE4OjQ2OjAzLjg2NDk1NFoiLCJlbWFpbCI6InNhcm1hZGM0NUBnbWFpbC5jb20ifV0sImNyZWF0ZWRfYXQiOiIyMDI1LTA3LTE4VDIxOjI5OjQ2LjM0ODA3NloiLCJ1cGRhdGVkX2F0IjoiMjAyNS0xMS0wNFQyMzoyMTowNC45MDMyNjRaIiwiaXNfY; sb-mddgtexrnnlctttbcpsy-auth-token.1=W5vbnltb3VzIjpmYWxzZX19"

# Trigger ingestion for all active sources
echo "Triggering ingestion for all active sources..."
echo ""

RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST "http://localhost:3000/api/admin/ingestion/run" \
  -H "Cookie: $COOKIE" \
  -H "Content-Type: application/json" \
  -d '{}')

# Extract HTTP status and body
HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS/d')

echo "HTTP Status: $HTTP_STATUS"
echo ""
echo "Response:"
echo "$BODY" | jq . 2>/dev/null || echo "$BODY"
echo ""

# Or trigger for a specific source (Techmeme Complete)
# echo "Triggering ingestion for Techmeme Events (Complete)..."
# curl -X POST "http://localhost:3000/api/admin/ingestion/run" \
#   -H "Cookie: $COOKIE" \
#   -H "Content-Type: application/json" \
#   -d '{"sourceId": "e79a3eef-7e92-41e5-9e8f-976392e27e9c"}' | jq .

