// src/app/layout.tsx (Corrected)

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import QueryProvider from '@/components/providers/QueryProvider';
import { AuthProvider } from "@/contexts/AuthContext";
import ClientLayout from "@/components/layout/ClientLayout";
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="bottom-right" richColors />
        <QueryProvider>
          <AuthProvider>
            <ClientLayout>
              {children}
            </ClientLayout>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}